library(BBmisc)
library(dplyr)
library(FishStatsUtils)
library(gdistance)
library(ggplot2)
library(gstat)
library(INLA)
library(maps)
library(maptools)  
library(patchwork)
library(plot.matrix)
library(RandomFields)
library(raster)
library(reshape2)
library(rnaturalearth)
library(rgdal)
library(scales)
library(sf)
library(sp) 
library(spData) ## For `world`, an sf MULTIPOLYGON object
library(spdep)
library(stars)
library(svMisc)
library(tidyverse)
library(TMB)
library(viridis)
library(virtualspecies)

world_sf <- ne_countries(scale = "medium", returnclass = "sf")

# Paths
project_spatialIPM <- "../Spatial_snow_crab_2021/" # to go to working directory related to spatial IPM
DateFile = paste0(getwd(), "/2_Max_spatial_projection/Outputs/")
if(!dir.exists(DateFile)) dir.create(DateFile)