library(reshape2)
library(dplyr)
library(viridis)
library(maps)
library(maptools)  
library(sf)
library(ggplot2)
library(dplyr)
library(sp) 
library(sf)
library(rgdal)
library(sf)
library(sp)
library(INLA)
library(RandomFields)
library(maptools)
library(ggplot2)
library(gstat)
library(BBmisc)
library(viridis)
library(patchwork)
library(raster)
library(spData) ## For `world`, an sf MULTIPOLYGON object
require(virtualspecies)
library(scales)
library(BBmisc)
library(reshape2)
library(gdistance)
library(raster)
library(maps)
library(maptools)
library(gdistance)
library(raster)
library(rnaturalearth)
library(svMisc)

world_sf <- ne_countries(scale = "medium", returnclass = "sf")
